version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - mongo
    environment:
      APP_PORT: "${APP_PORT:-3000}"
      MONGO_PORT: "${MONGO_PORT:-27017}"
      MONGO_DB_NAME: "${MONGO_DB_NAME:-santex-db}"
      EXTERNAL_API_URL: "${EXTERNAL_API_URL:-https://api.football-data.org/v4}"
      EXTERNAL_API_KEY: "${EXTERNAL_API_KEY:-5ce498aa927c4bb5adf7cfca37fad837}"
      MONGO_URI: "mongodb://mongo:${MONGO_PORT:-27017}/${MONGO_DB_NAME:-santex-db}"
  mongo:
    image: "mongo:latest"
    ports:
       - "${MONGO_PORT:-27017}:27017"